[tool.nixpacks]
enable = true

# ─────────── Setup Phase ───────────
[[tool.nixpacks.phases.setup]]
commands = [
  # install PHP deps
  "composer install --ignore-platform-reqs --no-interaction --prefer-dist --optimize-autoloader",
  # install JS deps
  "npm ci"
]

# ─────────── Build Phase ───────────
[[tool.nixpacks.phases.build]]
commands = [
  # clear any locally cached config so we don’t bake in HTTP URLs
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  # build your Vite assets
  "npm run build"
]

# ────────── Optimize Phase ──────────
# By default Nixpacks would run 'php artisan optimize:clear' which hits the DB.
# We replace it with a *no-DB* cache step:
[[tool.nixpacks.phases.optimize]]
commands = [
  # only cache files, routes & views (no DB calls)
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

# ─────────── Start Phase ───────────
[[tool.nixpacks.phases.start]]
commands = [
  # run your migrations & then serve on $PORT
  "php artisan migrate --force",
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]
