# railway.toml

# ————————— Build Step —————————
[build]
# Usamos Nixpacks en su modo V2 para poder definir preDeploy/start también
builder          = "NIXPACKS"
buildEnvironment = "V2"

# Ejecuta tus clears locales + build de assets en una línea
buildCommand     = """
php artisan config:clear \
  && php artisan route:clear \
  && php artisan view:clear \
  && npm ci \
  && npm run build
"""

# ————————— Deploy Step —————————
[deploy]
# Corre migraciones (y opcionalmente cachea config/rutas/vistas)
# dentro de la red privada, justo antes de arrancar.
preDeployCommand = [
  "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
]

# El comando para iniciar tu servidor Laravel en el port que Railway expone
startCommand     = "php artisan serve --host=0.0.0.0 --port=$PORT"

# Health check para validar que la app esté viva
healthcheckPath    = "/"
healthcheckTimeout = 30

# Política de reinicio por si falla
restartPolicyType  = "ON_FAILURE"
